# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dshem/Documents/these/test/detection_enhancer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dshem/Documents/these/test/detection_enhancer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dshem/Documents/these/test/detection_enhancer/CMakeFiles /home/dshem/Documents/these/test/detection_enhancer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dshem/Documents/these/test/detection_enhancer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kalman

# Build rule for target.
kalman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kalman
.PHONY : kalman

# fast build rule for target.
kalman/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/build
.PHONY : kalman/fast

#=============================================================================
# Target rules for targets named objecthistory

# Build rule for target.
objecthistory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 objecthistory
.PHONY : objecthistory

# fast build rule for target.
objecthistory/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objecthistory.dir/build.make CMakeFiles/objecthistory.dir/build
.PHONY : objecthistory/fast

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named genboxes

# Build rule for target.
genboxes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 genboxes
.PHONY : genboxes

# fast build rule for target.
genboxes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genboxes.dir/build.make CMakeFiles/genboxes.dir/build
.PHONY : genboxes/fast

src/genboxes.o: src/genboxes.cpp.o
.PHONY : src/genboxes.o

# target to build an object file
src/genboxes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genboxes.dir/build.make CMakeFiles/genboxes.dir/src/genboxes.cpp.o
.PHONY : src/genboxes.cpp.o

src/genboxes.i: src/genboxes.cpp.i
.PHONY : src/genboxes.i

# target to preprocess a source file
src/genboxes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genboxes.dir/build.make CMakeFiles/genboxes.dir/src/genboxes.cpp.i
.PHONY : src/genboxes.cpp.i

src/genboxes.s: src/genboxes.cpp.s
.PHONY : src/genboxes.s

# target to generate assembly for a file
src/genboxes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genboxes.dir/build.make CMakeFiles/genboxes.dir/src/genboxes.cpp.s
.PHONY : src/genboxes.cpp.s

src/kalman.o: src/kalman.cpp.o
.PHONY : src/kalman.o

# target to build an object file
src/kalman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/src/kalman.cpp.o
.PHONY : src/kalman.cpp.o

src/kalman.i: src/kalman.cpp.i
.PHONY : src/kalman.i

# target to preprocess a source file
src/kalman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/src/kalman.cpp.i
.PHONY : src/kalman.cpp.i

src/kalman.s: src/kalman.cpp.s
.PHONY : src/kalman.s

# target to generate assembly for a file
src/kalman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/src/kalman.cpp.s
.PHONY : src/kalman.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/objecthistory.o: src/objecthistory.cpp.o
.PHONY : src/objecthistory.o

# target to build an object file
src/objecthistory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objecthistory.dir/build.make CMakeFiles/objecthistory.dir/src/objecthistory.cpp.o
.PHONY : src/objecthistory.cpp.o

src/objecthistory.i: src/objecthistory.cpp.i
.PHONY : src/objecthistory.i

# target to preprocess a source file
src/objecthistory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objecthistory.dir/build.make CMakeFiles/objecthistory.dir/src/objecthistory.cpp.i
.PHONY : src/objecthistory.cpp.i

src/objecthistory.s: src/objecthistory.cpp.s
.PHONY : src/objecthistory.s

# target to generate assembly for a file
src/objecthistory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objecthistory.dir/build.make CMakeFiles/objecthistory.dir/src/objecthistory.cpp.s
.PHONY : src/objecthistory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... app"
	@echo "... genboxes"
	@echo "... kalman"
	@echo "... objecthistory"
	@echo "... src/genboxes.o"
	@echo "... src/genboxes.i"
	@echo "... src/genboxes.s"
	@echo "... src/kalman.o"
	@echo "... src/kalman.i"
	@echo "... src/kalman.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/objecthistory.o"
	@echo "... src/objecthistory.i"
	@echo "... src/objecthistory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

